"""add ttl_days

Revision ID: 42f2c209e2f6
Revises: 002
Create Date: 2026-06-10 17:15:19.758993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42f2c209e2f6'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_configs', sa.Column('email_notify', sa.Boolean(), nullable=False))
    op.add_column('memory_entries', sa.Column('ttl_days', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_users_firebase_uid'), table_name='users')
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.create_index(op.f('idx_users_firebase_uid'), 'users', ['firebase_uid'], unique=False)
    op.drop_column('memory_entries', 'ttl_days')
    op.drop_column('alert_configs', 'email_notify')
    # ### end Alembic commands ###
